# Coolify Deployment Configuration
version: "3.8"

# This file is specifically configured for Coolify deployment
# Coolify will handle SSL termination, so we don't need certbot here

services:
  # Next.js Application
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hireflutter-nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - WORDPRESS_API_URL=http://wordpress:80/wp-json/wp/v2
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`hirededicatedflutterdeveloper.com`) || Host(`www.hirededicatedflutterdeveloper.com`)"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3008"
    networks:
      - app-network
    depends_on:
      - wordpress

  # WordPress CMS
  wordpress:
    image: wordpress:6.4-php8.2-apache
    container_name: hireflutter-wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 0
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://hirededicatedflutterdeveloper.com/cms');
        define('WP_SITEURL', 'https://hirededicatedflutterdeveloper.com/cms');
        define('FORCE_SSL_ADMIN', true);
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
          $$_SERVER['HTTPS'] = 'on';
        }
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    labels:
      - "coolify.managed=true"
      - "coolify.type=service"
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`hirededicatedflutterdeveloper.com`) && PathPrefix(`/cms`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.http.middlewares.wordpress-strip.stripprefix.prefixes=/cms"
      - "traefik.http.routers.wordpress.middlewares=wordpress-strip"
    networks:
      - app-network
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hireflutter-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    labels:
      - "coolify.managed=true"
      - "coolify.type=database"
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  wordpress_data:
  mysql_data:

networks:
  app-network:
    driver: bridge
