# Nixpacks configuration with Node 20 + pinned pnpm to fix corepack signature issues
[variables]
NODE_ENV = "production"
NEXT_PUBLIC_GA_ID = "G-MHGSBBP95T"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.12.0 --activate",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"